services:
  api:
    container_name: api_container
    build: .
    environment:
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: tema2
      DB_HOST: postgres
      PORT: 6000
    ports:
      - "6000:6000"
    networks:
      - api-network

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tema2
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - postgres-network
      - api-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: andrei@email.ro
      PGADMIN_DEFAULT_PASSWORD: e-cool
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-network

networks:
  postgres-network:
  api-network:

volumes:
  postgres_data:
  pgadmin-data: